config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from corroserv_inventory.core.api.views import (
    confirm_convert_materials,
    convert_material_consumption,
)

# from django.views.generic import TemplateView
# from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    # Core App
    path("", include("corroserv_inventory.core.urls", namespace="core")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("corroserv_inventory.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    path(
        "api/confirm-convert-materials/",
        confirm_convert_materials,
        name="confirm_convert_materials",
    ),
    path(
        "api/convert-material-consumption/<int:convert_material_id>/<uuid:location_uuid>/",
        convert_material_consumption,
        name="convert_material_consumption",
    ),
    # DRF auth token
    # path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

corroserv_inventory/core/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

from . import views

app_name = "core"
urlpatterns = [
    path("", TemplateView.as_view(template_name="core/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="core/about.html"), name="about"),
    path("home/", views.home, name="home"),
    path(
        "view/",
        include(
            [
                # path("", views.view_all, name="view_all"),
                path("<str:item_type>/", views.view_specific, name="view_specific"),
            ]
        ),
    ),
    path(
        "create/",
        include(
            [
                path("<str:item_type>/", views.create, name="create"),
            ]
        ),
    ),
    path(
        "task/",
        include(
            [
                path(
                    "Convert/",
                    include(
                        [
                            path(
                                "select-product",
                                views.convert_select_product,
                                name="convert_select_product",
                            ),
                            path(
                                "materials/<uuid:product_uuid>/",
                                views.convert_materials,
                                name="convert_materials",
                            ),
                            path(
                                "main/<int:convert_task_id>/",
                                views.convert_task_main,
                                name="convert_task_main",
                            ),
                            path(
                                "main/<int:convert_task_id>/<int:convert_material_id>/",
                                views.convert_material_locations,
                                name="convert_material_locations",
                            ),
                            path(
                                "main/<int:convert_task_id>/<int:convert_material_id>/<uuid:location_uuid>/",
                                views.convert_material_consumption,
                                name="convert_material_consumption",
                            ),
                            path(
                                "confirm/<int:convert_task_id>/",
                                views.convert_confirm_product_quantity,
                                name="convert_confirm_product_quantity",
                            ),
                        ]
                    ),
                ),
                path("<str:task_type>/", views.task, name="task"),
                path(
                    "<str:task_type>/select_item/",
                    views.task_select_item,
                    name="task_select_item",
                ),
                path(
                    "<str:task_type>/<uuid:item_uuid>/",
                    views.task_confirm,
                    name="task_confirm",
                ),
                path("<int:task_id>/details/", views.task_details, name="task_details"),
            ]
        ),
    ),
]

corroserv_inventory/users/urls.py
from django.urls import path

from corroserv_inventory.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

corroserv_inventory/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for corroserv_inventory."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

corroserv_inventory/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

corroserv_inventory/core/api/views.py
import uuid

from django.contrib.auth.decorators import login_required
from django.db import transaction
from rest_framework import status, viewsets
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from corroserv_inventory.core.models import (
    ConvertMaterial,
    ConvertMaterialConsumption,
    Inventory,
    Item,
    Location,
    SingleOpenInventory,
    Task,
)

from .serializers import ItemSerializer


class MaterialViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)
    queryset = Item.objects.filter(type__name="Material")
    serializer_class = ItemSerializer


@login_required
@api_view(["POST"])
def confirm_convert_materials(request):

    if request.data:
        product = Item.objects.get(uuid=request.data["product_uuid"])
        selected_materials = [
            Item.objects.get(pk=material["id"])
            for material in request.data["selectedMaterials"]
        ]

    convertTaskId = Task.objects.create_convert_task(
        "Convert", product, selected_materials
    )

    return Response(
        {
            "message": "Added conversion materials",
            "convertTaskId": convertTaskId,
        },
        status=status.HTTP_200_OK,
    )


@login_required
@api_view(["GET", "POST"])
def convert_material_consumption(
    request, convert_material_id: int, location_uuid: uuid
):
    convert_material = ConvertMaterial.objects.get(pk=convert_material_id)
    convert_material_inventory = Inventory.objects.get(
        item=convert_material.item,
        location=Location.objects.get(uuid=location_uuid),
    )

    if request.data:
        consumptionArray = request.data["consumptionArray"]

        with transaction.atomic():
            for item in consumptionArray:

                capacity = convert_material.item.size
                remaining = float(item["quantity"])

                if item["status"] == "Open":

                    open_inventory_item = SingleOpenInventory.objects.get(
                        pk=item["open_inventory_id"]
                    )
                    consumed = open_inventory_item.remaining - remaining

                    if remaining == 0:
                        completely_consumed = True
                    else:
                        completely_consumed = False

                elif item["status"] == "Unopened":

                    open_inventory_item = None
                    consumed = capacity - remaining

                    if remaining == 0:
                        completely_consumed = True

                    else:
                        completely_consumed = False

                else:
                    print("HANDLE ERROR")

                ConvertMaterialConsumption.objects.create(
                    convert_material=convert_material,
                    inventory_item=convert_material_inventory,
                    consume_amount=consumed,
                    completely_consumed=completely_consumed,
                    open_inventory=open_inventory_item,
                )

        return Response(
            {
                "message": "Added conversion material consumption",
                # "convertTaskId": convertTaskId,
            },
            status=status.HTTP_200_OK,
        )

    else:
        convert_material_inventory_serialized = []

        open_inventory = convert_material_inventory.open_inventory_items.all()
        for opened_item in open_inventory:
            convert_material_inventory_serialized.append(
                {
                    "id": opened_item.inventory_item.id,
                    "name": opened_item.inventory_item.item.name,
                    "location": opened_item.inventory_item.location.name,
                    "status": "Open",
                    "open_inventory_id": opened_item.id,
                    "remaining": opened_item.remaining,
                }
            )
        for unopened_item in range(
            convert_material_inventory.quantity - len(open_inventory)
        ):
            convert_material_inventory_serialized.append(
                {
                    "id": convert_material_inventory.id,
                    "name": convert_material_inventory.item.name,
                    "location": convert_material_inventory.location.name,
                    "status": "Unopened",
                    "open_inventory_id": None,
                    "remaining": f"{convert_material_inventory.item.size}",
                }
            )
        return Response(
            {
                "message": "Material details retrieval success!",
                "convert_material": convert_material_inventory_serialized,
            },
            status=status.HTTP_200_OK,
        )

corroserv_inventory/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

corroserv_inventory/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

corroserv_inventory/templates/includes/configuration-plugin.html
        <div class="custom-template">
			<div class="title">Settings</div>
			<div class="custom-content">
				<div class="switcher">
					<div class="switch-block">
						<h4>Logo Header</h4>
						<div class="btnSwitch">
							<button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
							<button type="button" class="selected changeLogoHeaderColor" data-color="blue"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="green"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="red"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="white"></button>
							<br/>
							<button type="button" class="changeLogoHeaderColor" data-color="dark2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Navbar Header</h4>
						<div class="btnSwitch">
							<button type="button" class="changeTopBarColor" data-color="dark"></button>
							<button type="button" class="changeTopBarColor" data-color="blue"></button>
							<button type="button" class="changeTopBarColor" data-color="purple"></button>
							<button type="button" class="changeTopBarColor" data-color="light-blue"></button>
							<button type="button" class="changeTopBarColor" data-color="green"></button>
							<button type="button" class="changeTopBarColor" data-color="orange"></button>
							<button type="button" class="changeTopBarColor" data-color="red"></button>
							<button type="button" class="changeTopBarColor" data-color="white"></button>
							<br/>
							<button type="button" class="changeTopBarColor" data-color="dark2"></button>
							<button type="button" class="selected changeTopBarColor" data-color="blue2"></button>
							<button type="button" class="changeTopBarColor" data-color="purple2"></button>
							<button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
							<button type="button" class="changeTopBarColor" data-color="green2"></button>
							<button type="button" class="changeTopBarColor" data-color="orange2"></button>
							<button type="button" class="changeTopBarColor" data-color="red2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Sidebar</h4>
						<div class="btnSwitch">
							<button type="button" class="selected changeSideBarColor" data-color="white"></button>
							<button type="button" class="changeSideBarColor" data-color="dark"></button>
							<button type="button" class="changeSideBarColor" data-color="dark2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Background</h4>
						<div class="btnSwitch">
							<button type="button" class="changeBackgroundColor" data-color="bg2"></button>
							<button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
							<button type="button" class="changeBackgroundColor" data-color="bg3"></button>
							<button type="button" class="changeBackgroundColor" data-color="dark"></button>
						</div>
					</div>
				</div>
			</div>
			<div class="custom-toggle">
				<i class="flaticon-settings"></i>
			</div>
		</div>

corroserv_inventory/templates/includes/footer.html
<footer class="footer">
	<div class="container-fluid">
		<nav class="pull-left">
			<ul class="nav">
				<li class="nav-item">
					<a class="nav-link" target="_blank" href="https://appseed.us/admin-dashboards/django-dashboard-atlantis-dark">
						Django Atlantis Dark
					</a>
				</li>
			</ul>
		</nav>
		<div class="copyright ml-auto">
			&copy; <a target="_blank" href="https://www.themekita.com">ThemeKita</a>
			- coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
		</div>
	</div>
</footer>

corroserv_inventory/templates/includes/scripts.html
{% load static %}

<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.3.2.1.min.js' %}"></script>
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>

<!-- jQuery UI -->
<script src="{% static 'js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js' %}"></script>

<!-- jQuery Scrollbar -->
<script src="{% static 'js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>

<!-- Chart JS -->
<script src="{% static 'js/plugin/chart.js/chart.min.js' %}"></script>

<!-- jQuery Sparkline -->
<script src="{% static 'js/plugin/jquery.sparkline/jquery.sparkline.min.js' %}"></script>

<!-- Chart Circle -->
<script src="{% static 'js/plugin/chart-circle/circles.min.js' %}"></script>

<!-- Datatables -->
<script src="{% static 'js/plugin/datatables/datatables.min.js' %}"></script>

<!-- Bootstrap Notify -->
<script src="{% static 'js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script>

<!-- jQuery Vector Maps -->
<script src="{% static 'js/plugin/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'js/plugin/jqvmap/maps/jquery.vmap.world.js' %}"></script>

<!-- Sweet Alert -->
<script src="{% static 'js/plugin/sweetalert/sweetalert.min.js' %}"></script>

<!-- Atlantis JS -->
<script src="{% static 'js/atlantis.min.js' %}"></script>

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="{% static 'js/setting-demo.js' %}"></script>
<script src="{% static 'js/demo.js' %}"></script>
<script>
	Circles.create({
		id: 'circles-1',
		radius: 45,
		value: 60,
		maxValue: 100,
		width: 7,
		text: 5,
		colors: ['#f1f1f1', '#FF9E27'],
		duration: 400,
		wrpClass: 'circles-wrp',
		textClass: 'circles-text',
		styleWrapper: true,
		styleText: true
	})

	Circles.create({
		id: 'circles-2',
		radius: 45,
		value: 70,
		maxValue: 100,
		width: 7,
		text: 36,
		colors: ['#f1f1f1', '#2BB930'],
		duration: 400,
		wrpClass: 'circles-wrp',
		textClass: 'circles-text',
		styleWrapper: true,
		styleText: true
	})

	Circles.create({
		id: 'circles-3',
		radius: 45,
		value: 40,
		maxValue: 100,
		width: 7,
		text: 12,
		colors: ['#f1f1f1', '#F25961'],
		duration: 400,
		wrpClass: 'circles-wrp',
		textClass: 'circles-text',
		styleWrapper: true,
		styleText: true
	})

	var totalIncomeChart = document.getElementById('totalIncomeChart').getContext('2d');

	var mytotalIncomeChart = new Chart(totalIncomeChart, {
		type: 'bar',
		data: {
			labels: ["S", "M", "T", "W", "T", "F", "S", "S", "M", "T"],
			datasets: [{
				label: "Total Income",
				backgroundColor: '#ff9e27',
				borderColor: 'rgb(23, 125, 255)',
				data: [6, 4, 9, 5, 4, 6, 4, 3, 8, 10],
			}],
		},
		options: {
			responsive: true,
			maintainAspectRatio: false,
			legend: {
				display: false,
			},
			scales: {
				yAxes: [{
					ticks: {
						display: false //this will remove only the label
					},
					gridLines: {
						drawBorder: false,
						display: false
					}
				}],
				xAxes: [{
					gridLines: {
						drawBorder: false,
						display: false
					}
				}]
			},
		}
	});

	$('#lineChart').sparkline([105, 103, 123, 100, 95, 105, 115], {
		type: 'line',
		height: '70',
		width: '100%',
		lineWidth: '2',
		lineColor: '#ffa534',
		fillColor: 'rgba(255, 165, 52, .14)'
	});
</script>

corroserv_inventory/templates/includes/sidebar.html
<!-- Sidebar -->
<div class="sidebar sidebar-style-2" data-background-color="dark2">
	<div class="sidebar-wrapper scrollbar scrollbar-inner">
		<div class="sidebar-content">

			{% if request.user.is_authenticated %}
			<div class="user">
				<div class="avatar-sm float-left mr-2">
					<img src="#" alt="..." class="avatar-img rounded-circle">
					<!-- <img src="/static/assets/img/profile.jpg" alt="..." class="avatar-img rounded-circle"> -->
				</div>
				<div class="info">
					<a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
						<span>
							{{ request.user.username }}
							<span class="user-level">
								{{ request.user.email }}
							</span>
							<span class="caret"></span>
						</span>
					</a>
					<div class="clearfix"></div>

					<div class="collapse in" id="collapseExample">
						<ul class="nav">
							<li>
								<a href="#profile">
									<span class="link-collapse">My Profile</span>
								</a>
							</li>
							<li>
								<a href="#">
									<span class="link-collapse">Logout</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<ul class="nav nav-primary">
				<li class="nav-section">
					<span class="sidebar-mini-icon">
						<i class="fa fa-ellipsis-h"></i>
					</span>
					<h4 class="text-section">View</h4>
				</li>
				<li class="nav-item {% if 'index' in segment %} active {% endif %}">
					<a data-toggle="collapse" href="#dashboard" class="collapsed" aria-expanded="false">
						<i class="fas fa-home"></i>
						<p>Dashboard</p>
						<span class="caret"></span>
					</a>
					<div class="collapse" id="dashboard">
						<ul class="nav nav-collapse">
							<li>
								<a href="/index.html">
									<span class="sub-item">Analytics</span>
								</a>
							</li>
							<li>
								<a href="/index.html">
									<span class="sub-item">Reporting</span>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<li class="nav-item {% if 'index' in segment %} active {% endif %}">
					<a data-toggle="collapse" href="#items" class="collapsed" aria-expanded="false">
						<i class="fas fa-barcode"></i>
						<p>Items</p>
						<span class="caret"></span>
					</a>
					<div class="collapse" id="items">
						<ul class="nav nav-collapse">
							<li>
								<a href="{% url 'core:view_specific' 'Material' %}">
									<span class="sub-item">Materials</span>
								</a>
							</li>
							<li>
								<a href="{% url 'core:view_specific' 'Product' %}">
									<span class="sub-item">Products</span>
								</a>
							</li>
							<li>
								<a href="{% url 'core:view_specific' 'Consumable' %}">
									<span class="sub-item">Consumables</span>
								</a>
							</li>
							<li>
								<a href="{% url 'core:view_specific' 'Tool' %}">
									<span class="sub-item">Tools</span>
								</a>
							</li>
							<li>
								<a href="{% url 'core:view_specific' 'Fiber' %}">
									<span class="sub-item">Fibers</span>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<li class="nav-item">
					<a data-toggle="collapse" href="#tasks">
						<i class="fas fa-clipboard"></i>
						<p>Tasks</p>
						<span class="caret"></span>
					</a>
					<div class="collapse" id="tasks">
						<ul class="nav nav-collapse">
							<li>
								<a href="{% url 'core:task' 'Consume' %}">
									<span class="sub-item">Consume</span>
								</a>
							</li>
							<li>
								<a href="{% url 'core:task' 'Convert' %}">
									<span class="sub-item">Convert</span>
								</a>
							</li>
							<li>
								<a data-toggle="collapse" href="#movementTasks">
									<span class="sub-item">Movement</span>
									<span class="caret"></span>
								</a>
								<div class="collapse" id="movementTasks">
									<ul class="nav nav-collapse subnav">
										<li>
											<a href="{% url 'core:task' 'Inbound' %}">
												<span class="sub-item">Inbound</span>
											</a>
										</li>
										<li>
											<a href="{% url 'core:task' 'Outbound' %}">
												<span class="sub-item">Outbound</span>
											</a>
										</li>
										<li>
											<a href="{% url 'core:task' 'Transfer' %}">
												<span class="sub-item">Transfer</span>
											</a>
										</li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li class="nav-section">
					<span class="sidebar-mini-icon">
						<i class="fa fa-ellipsis-h"></i>
					</span>
					<h4 class="text-section">Create</h4>
				</li>
				<li class="nav-item {% if 'ui-' in segment %} active {% endif %}">
					<a data-toggle="collapse" href="#createItems">
						<i class="fas fa-barcode"></i>
						<p>Item</p>
						<span class="caret"></span>
					</a>
					<div class="collapse" id="createItems">
						<ul class="nav nav-collapse">
							<li>
								<a href="{% url 'core:create' 'Material' %}">
									<span class="sub-item">Material</span>
								</a>
							</li>
							<li>
								<a href="{% url 'core:create' 'Product' %}">
									<span class="sub-item">Product</span>
								</a>
							</li>
							<li>
								<a href="{% url 'core:create' 'Consumable' %}">
									<span class="sub-item">Consumable</span>
								</a>
							</li>
							<li>
								<a href="{% url 'core:create' 'Tool' %}">
									<span class="sub-item">Tool</span>
								</a>
							</li>
							<li>
								<a href="{% url 'core:create' 'Fiber' %}">
									<span class="sub-item">Fiber</span>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<li class="nav-item">
					<a data-toggle="collapse" href="#createTask">
						<i class="fas fa-clipboard"></i>
						<p>Task</p>
						<span class="caret"></span>
					</a>
					<div class="collapse" id="createTask">
						<ul class="nav nav-collapse">
							<li>
								<a href="{% url 'core:task_select_item' 'Consume' %}">
									<span class="sub-item">Consume</span>
								</a>
							</li>
							<li>
								<a href="{% url 'core:convert_select_product' %}">
									<span class="sub-item">Convert</span>
								</a>
							</li>
							<li>
								<a data-toggle="collapse" href="#createMovementTask">
									<span class="sub-item">Movement</span>
									<span class="caret"></span>
								</a>
								<div class="collapse" id="createMovementTask">
									<ul class="nav nav-collapse subnav">
										<li>
											<a href="{% url 'core:task_select_item' 'Inbound' %}">
												<span class="sub-item">Inbound</span>
											</a>
										</li>
										<li>
											<a href="{% url 'core:task_select_item' 'Outbound' %}">
												<span class="sub-item">Outbound</span>
											</a>
										</li>
										<li>
											<a href="{% url 'core:task_select_item' 'Transfer' %}">
												<span class="sub-item">Transfer</span>
											</a>
										</li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
				</li>
			</ul>
			{% else %}
			<ul class="nav nav-primary">
				<li class="mx-4 mt-2">
					<a target="_blank" href="https://appseed.us/admin-dashboards/django-dashboard-atlantis-dark-pro"
						class="btn btn-danger btn-block">
						<span class="btn-label mr-2"> <i class="fa fa-rocket"></i> </span>PRO Version</a>
				</li>
			</ul>
			{% endif %}
		</div>
	</div>
</div>
<!-- End Sidebar -->