config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from corroserv_inventory.core.api.views import (
    confirm_convert_materials,
    convert_material_consumption,
)

# from django.views.generic import TemplateView
# from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    # Core App
    path("", include("corroserv_inventory.core.urls", namespace="core")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("corroserv_inventory.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    path(
        "api/confirm-convert-materials/",
        confirm_convert_materials,
        name="confirm_convert_materials",
    ),
    path(
        "api/convert-material-consumption/<int:convert_material_id>/<uuid:location_uuid>/",
        convert_material_consumption,
        name="convert_material_consumption",
    ),
    # DRF auth token
    # path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

corroserv_inventory/core/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

from . import views

app_name = "core"
urlpatterns = [
    path("", TemplateView.as_view(template_name="core/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="core/about.html"), name="about"),
    path("home/", views.home, name="home"),
    path(
        "view/",
        include(
            [
                # path("", views.view_all, name="view_all"),
                path("<str:item_type>/", views.view_specific, name="view_specific"),
            ]
        ),
    ),
    path(
        "create/",
        include(
            [
                path("<str:item_type>/", views.create, name="create"),
            ]
        ),
    ),
    path(
        "task/",
        include(
            [
                path(
                    "Convert/",
                    include(
                        [
                            path(
                                "select-product",
                                views.convert_select_product,
                                name="convert_select_product",
                            ),
                            path(
                                "materials/<uuid:product_uuid>/",
                                views.convert_materials,
                                name="convert_materials",
                            ),
                            path(
                                "main/<int:convert_task_id>/",
                                views.convert_task_main,
                                name="convert_task_main",
                            ),
                            path(
                                "main/<int:convert_task_id>/<int:convert_material_id>/",
                                views.convert_material_locations,
                                name="convert_material_locations",
                            ),
                            path(
                                "main/<int:convert_task_id>/<int:convert_material_id>/<uuid:location_uuid>/",
                                views.convert_material_consumption,
                                name="convert_material_consumption",
                            ),
                            path(
                                "confirm/<int:convert_task_id>/",
                                views.convert_confirm_product_quantity,
                                name="convert_confirm_product_quantity",
                            ),
                        ]
                    ),
                ),
                path("<str:task_type>/", views.task, name="task"),
                path(
                    "<str:task_type>/select_item/",
                    views.task_select_item,
                    name="task_select_item",
                ),
                path(
                    "<str:task_type>/<uuid:item_uuid>/",
                    views.task_confirm,
                    name="task_confirm",
                ),
                path("<int:task_id>/details/", views.task_details, name="task_details"),
            ]
        ),
    ),
]

corroserv_inventory/users/urls.py
from django.urls import path

from corroserv_inventory.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

corroserv_inventory/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for corroserv_inventory."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

corroserv_inventory/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

corroserv_inventory/core/api/views.py
import uuid

from django.contrib.auth.decorators import login_required
from django.db import transaction
from rest_framework import status, viewsets
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from corroserv_inventory.core.models import (
    ConvertMaterial,
    ConvertMaterialConsumption,
    Inventory,
    Item,
    Location,
    SingleOpenInventory,
    Task,
)

from .serializers import ItemSerializer


class MaterialViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)
    queryset = Item.objects.filter(type__name="Material")
    serializer_class = ItemSerializer


@login_required
@api_view(["POST"])
def confirm_convert_materials(request):

    if request.data:
        product = Item.objects.get(uuid=request.data["product_uuid"])
        selected_materials = [
            Item.objects.get(pk=material["id"])
            for material in request.data["selectedMaterials"]
        ]

    convertTaskId = Task.objects.create_convert_task(
        "Convert", product, selected_materials
    )

    return Response(
        {
            "message": "Added conversion materials",
            "convertTaskId": convertTaskId,
        },
        status=status.HTTP_200_OK,
    )


@login_required
@api_view(["GET", "POST"])
def convert_material_consumption(
    request, convert_material_id: int, location_uuid: uuid
):
    convert_material = ConvertMaterial.objects.get(pk=convert_material_id)
    convert_material_inventory = Inventory.objects.get(
        item=convert_material.item,
        location=Location.objects.get(uuid=location_uuid),
    )

    if request.data:
        consumptionArray = request.data["consumptionArray"]

        with transaction.atomic():
            for item in consumptionArray:

                capacity = convert_material.item.size
                remaining = float(item["quantity"])

                if item["status"] == "Open":

                    open_inventory_item = SingleOpenInventory.objects.get(
                        pk=item["open_inventory_id"]
                    )
                    consumed = open_inventory_item.remaining - remaining

                    if remaining == 0:
                        completely_consumed = True
                    else:
                        completely_consumed = False

                elif item["status"] == "Unopened":

                    open_inventory_item = None
                    consumed = capacity - remaining

                    if remaining == 0:
                        completely_consumed = True

                    else:
                        completely_consumed = False

                else:
                    print("HANDLE ERROR")

                ConvertMaterialConsumption.objects.create(
                    convert_material=convert_material,
                    inventory_item=convert_material_inventory,
                    consume_amount=consumed,
                    completely_consumed=completely_consumed,
                    open_inventory=open_inventory_item,
                )

        return Response(
            {
                "message": "Added conversion material consumption",
                # "convertTaskId": convertTaskId,
            },
            status=status.HTTP_200_OK,
        )

    else:
        convert_material_inventory_serialized = []

        open_inventory = convert_material_inventory.open_inventory_items.all()
        for opened_item in open_inventory:
            convert_material_inventory_serialized.append(
                {
                    "id": opened_item.inventory_item.id,
                    "name": opened_item.inventory_item.item.name,
                    "location": opened_item.inventory_item.location.name,
                    "status": "Open",
                    "open_inventory_id": opened_item.id,
                    "remaining": opened_item.remaining,
                }
            )
        for unopened_item in range(
            convert_material_inventory.quantity - len(open_inventory)
        ):
            convert_material_inventory_serialized.append(
                {
                    "id": convert_material_inventory.id,
                    "name": convert_material_inventory.item.name,
                    "location": convert_material_inventory.location.name,
                    "status": "Unopened",
                    "open_inventory_id": None,
                    "remaining": f"{convert_material_inventory.item.size}",
                }
            )
        return Response(
            {
                "message": "Material details retrieval success!",
                "convert_material": convert_material_inventory_serialized,
            },
            status=status.HTTP_200_OK,
        )

corroserv_inventory/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

corroserv_inventory/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

corroserv_inventory/templates/includes/datatables/inventory_item_datatable.html
{% load static %}

<div class="table-responsive">
  <table id="basic-datatables" class="display table table-striped table-hover">
    <thead>
      <tr>
        <th>Item</th>
        <th>SKU</th>
        <th>Type</th>
        <th>Location</th>
        <th>Total</th>
        {% if page_type == "select_task" %}
        <th></th>
        {% endif %}
        {% if item_type == "Material" %}
        <th>(Openeded)</th>
        {% endif %}
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th>Item</th>
        <th>SKU</th>
        <th>Type</th>
        <th>Location</th>
        <th>Quantity</th>
        {% if page_type == "select_task" %}
        <th></th>
        {% endif %}
      </tr>
    </tfoot>
    <tbody>
      {% for inventory_item in inventory_listing %}
      <tr>
        <td>{{ inventory_item.item.name }}</td>
        {% if inventory_item.item.sku %}
        <td>{{ inventory_item.item.sku }}</td>
        {% else %}
        <td>-</td>
        {% endif %}
        <td>{{ inventory_item.item.type.name }}</td>
        <td>{{ inventory_item.location.name }}</td>
        <td>{{ inventory_item.quantity }}</td>
        {% if page_type == "select_task" %}
        <td>
          <a type="button" class="btn btn-success mb-3"
            href="{% url 'core:task_confirm' task_type inventory_item.item.uuid %}?inventory={{ inventory_item.id }}">Select</a>
        </td>
        {% elif page_type == "select_material" %}
        <td>
          {% if inventory_item.id in consumption_list_inventory_item_ids %}
          <button disabled class="btn btn-done mb-3">Done</button>
          {% else %}
          <a type="button" class="btn btn-success mb-3"
            href="{% url 'core:convert_material_consumption' convert_task_id material.id inventory_item.location.uuid %}">Select</a>
          {% endif %}
        </td>
        {% endif %}
        {% if item_type == "Material" %}
        <td>{{ inventory_item.open_inventory_count }}</td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

corroserv_inventory/templates/includes/datatables/material_datatable.html
{% load static %}

<div class="table-responsive">
  <table id="basic-datatables" class="display table table-striped table-hover">
    <thead>
      <tr>
        <th>Item</th>
        <th>Type</th>
        <th></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th>Item</th>
        <th>Type</th>
        <th></th>
      </tr>
    </tfoot>
    <tbody>
      {% for material in material_listing %}
      <tr>
        <td>{{ material.item.name }}</td>
        <td>{{ material.item.type.name }}</td>
        <td>
          {% if material.item.id in consumption_list_item_ids %}
          <button disabled class="btn btn-done mb-3">Done</button>
          {% else %}
          <a type="button" class="btn btn-success mb-3"
            href="{% url 'core:convert_material_locations' convert_task_id material.id %}">Start</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

corroserv_inventory/templates/includes/datatables/movement_item.html
{% load static %}

<div class="table-responsive">
  <table id="basic-datatables" class="display table table-striped table-hover">
    <thead>
      <tr>
        <th>Item</th>
        <th>Type</th>
        <th>Location</th>
        <th>Quantity</th>
        {% if page_type != "confirm_movement" %}
        <th></th>
        {% endif %}
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th>Item</th>
        <th>Type</th>
        <th>Location</th>
        <th>Quantity</th>
        {% if page_type != "confirm_movement" %}
        <th></th>
        {% endif %}
      </tr>
    </tfoot>
    <tbody>
      {% for inventory_item in inventory_listing %}
      <tr>
        <td>{{ inventory_item.item.name }}</td>
        <td>{{ inventory_item.item.type.name }}</td>
        <td>{{ inventory_item.location.name }}</td>
        <td>{{ inventory_item.quantity }}</td>
        {% if page_type != "confirm_movement" %}
        <td>
          <button class="btn btn-success mb-3">
            <a
              href="{% url 'core:movement_confirm' movement_type inventory_item.item.uuid inventory_item.id %}">Select</a>
          </button>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

corroserv_inventory/templates/includes/datatables/product_datatable.html
{% load static %}

<div class="table-responsive">
  <table id="basic-datatables" class="display table table-striped table-hover">
    <thead>
      <tr>
        <th>Item</th>
        <th>Type</th>
        <th></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th>Item</th>
        <th>Type</th>
        <th></th>
      </tr>
    </tfoot>
    <tbody>
      {% for product in product_listing %}
      <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.type.name }}</td>
        <td>
          <a type="button" class="btn btn-success mb-3"
            href="{% url 'core:convert_materials' product.uuid %}">Select</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

corroserv_inventory/templates/includes/datatables/task_datatable.html
{% load static %}

<div class="table-responsive">
  <table id="basic-datatables" class="display table table-striped table-hover">
    <thead>
      <tr>
        <th>Task</th>
        <th>Type</th>
        <th>Item</th>
        {% if task_type == 'Transfer' %}
        <th>From Location</th>
        <th>To Location</th>
        {% else %}
        <th>Location</th>
        {% endif %}
        <th>Quantity</th>
        <th>Status</th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th>Task</th>
        <th>Type</th>
        <th>Item</th>
        <th>Location</th>
        <th>Quantity</th>
        <th>Status</th>
      </tr>
    </tfoot>
    <tbody>
      {% for task in task_listing %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ task.type.name }}</td>
        <td>{{ task.item.name }}</td>
        {% if task_type == 'Transfer' %}
        <td>{{ task.transfer_from_location }}</td>
        <!-- <td>INSERT FROM LOCATION</td> -->
        <td>{{ task.location }}</td>
        {% else %}
        <td>
          {% if task.location.name == None %}
          Pending
          {% else %}
          {{ task.location.name }}
          {% endif %}
        </td>
        {% endif %}
        <td>
          {% if task.quantity == None %}
          Pending
          {% else %}
          {{ task.quantity }}
          {% endif %}
        </td>
        <td>
          <a href="{% url 'core:task_details' task.id %}">{{ task.latest_status }}</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>